name: BuddyToBody
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google_maps_flutter: ^0.5.21+7
  # geocoder: ^0.2.1
  # geolocator: ^5.1.4+1
  # location: ^2.3.5
  # firebase_database: ^3.0.7
  # flutter_full_pdf_viewer: ^1.0.6
  # cached_network_image: ^1.1.1
  # path_provider: ^1.3.0
  # flutter_launcher_icons: ^0.7.3
  # splashscreen: ^1.2.0

  # pdftron_flutter:
  #   git:
  #     url: git://github.com/PDFTron/pdftron-flutter.git

  permission: ^0.1.5
  google_maps_flutter: ^0.5.19
  geocoder: ^0.1.1
  geolocator: ^5.0.1
  location: ^2.3.5
  firebase_database: ^3.0.4
  flutter_full_pdf_viewer: ^1.0.4
  cached_network_image: ^2.0.0-rc
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_pdfview: ^1.0.0+9

  path_provider: ^1.2.0
  flutter_launcher_icons: ^0.7.2+1
  splashscreen: ^1.2.0
  pedometer: ^1.0.0
  google_map_polyline: ^0.2.0+1
  flutter_polyline_points: ^0.1.0
  firebase_messaging: ^6.0.9
  background_fetch: ^0.5.4
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git

  # firebase_analytics: ^1.0.4
  # firebase_auth:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  # firebase_core: ^0.4.0+9
  # firebase_auth: ^0.14.0+5
  # goog
  firebase_core: ^0.4.0+6
  firebase_auth: 0.11.1+11
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.1
  flutter_auth_buttons: ^0.3.1
  image_picker: ^0.6.0+10
  image_cropper: ^1.0.2
  cloud_firestore: 0.12.7
  shared_preferences: ^0.5.3+4
  fluttertoast: ^3.1.0
  firebase_storage: 3.0.3
  flutter_twitter_login: ^1.1.0
  http: ^0.12.0+4

  intl: ^0.16.0
  toast: ^0.1.5
  flutter_dash: ^0.0.1
  latlong: ^0.6.1
  flutter_local_notifications: ^1.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/AppIconMedium.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  #   - family: facebook
  #     fonts:
  #       - assets: assets/fonts/facebook.ttf

  assets:
    - assets/images/
